version: '3.1'

services:
 mysql-db:
  build: ./mysql
  restart: always
  command:
   - --character-set-server=utf8mb4
   - --collation-server=utf8mb4_unicode_ci
  environment:
   MYSQL_ROOT_PASSWORD: hdcpptd123.
  ports:
  - "3306:3306"
  volumes:
  - /my/own/datadir:/var/lib/mysql